# 1. Thông tin Service
spring.application.name=order-service
server.port=8082

# 2. Cấu hình PostgreSQL (Sử dụng biến môi trường hoặc mặc định Localhost)
# Lưu ý: Khi chạy trong Docker, hãy đảm bảo cổng 5434 đã được map ra ngoài máy thật.
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5434/ecommerce_order_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Cấu hình Kafka (Trỏ tới localhost hoặc service kafka trong Docker)
# Khi chạy Local, kafka ở localhost:9092. Khi trong Docker, kafka ở kafka:9092.
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# 4. Đăng ký Eureka Server (Tổng đài)
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
eureka.instance.prefer-ip-address=true
# 5. Cấu hình Tracing (Zipkin)
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# 6. Các cấu hình phụ trợ khác
spring.jpa.properties.hibernate.format_sql=true