spring.application.name=product-service
server.port=8081

# 1. Cấu hình kết nối PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_product_db
spring.datasource.username=postgres
spring.datasource.password=Dien_Mat_Khau_Postgres_Cua_Ban
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Cấu hình Hibernate tự động tạo bảng dữ liệu
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. Đăng ký với Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Cho phép ghi đè Bean (đã fix từ trước)
spring.main.allow-bean-definition-overriding=true