spring.application.name=product-service
server.port=8081

# 1. Cấu hình kết nối PostgreSQL
spring.datasource.url=jdbc:postgresql://product-db:5432/product_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Cấu hình Hibernate tự động tạo bảng dữ liệu
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. Đăng ký với Eureka Server
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
eureka.instance.prefer-ip-address=true

# Cho phép ghi đè Bean (đã fix từ trước)
spring.main.allow-bean-definition-overriding=true

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin-server:9411/api/v2/spans